version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/url_shortener
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=https://auth.dev.hr.alabuga.space/realms/Alabuga
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=https://auth.dev.hr.alabuga.space/realms/Alabuga/protocol/openid-connect/certs
    depends_on:
      - db
    networks:
      - shortener-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=url_shortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shortener-network

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Копируем конфигурацию Nginx
      - /etc/letsencrypt:/etc/letsencrypt # Сохраняем сертификаты SSL
    restart: always # Перезагружаем при каждом падении контейнера

volumes:
  postgres_data:

networks:
  shortener-network:
    driver: bridge
